几个小bug
renyuneyun/inforec pull request #1
Opened 2021-05-18 08:35 UTC by jxlxy1995

# bugList

1. sede.py中datetime使用方法 √  
2. obj.date.strftime(DATE_REPR)格式化出的内容对于时区会出现[]的情况，是否考虑去掉这个格式或者换一个格式化函数
3. model.py中_add_rel未判other是否为空，目前传入会出现异常 √ 
4. get_event中如果遇到非event类型数据直接抛出异常，是否不妥 √
5. DATETIME_REPR我查到的python3对于时间戳时区格式一定要是大写'Z'，否则会报异常 √  

# other

1. 建议加个日志，我个人感觉目前好几个抛出异常的地方，都只应该是errorLog或者warningLog的级别（比如get_event那个）。记录log即可，很多逻辑可以继续走下去的

2021-05-19 22:45 UTC, renyuneyun commented
那3个我没法拆分，得你来。。。都是按分支自动追踪HEAD的，所以你把你的master更新了以后新的就会上来。
解决方法嘛……就是强行让你的master倒退一个commit。然后你可以把那个第三个commit放在另一个分支里，推上来，然后创建PR。

记得先创建新分支，然后再改master的revision，不然还得费功夫把那个commit找回来。
比如可以按下面这样执行，然后创建新的PR就行：
```
git switch -c my-awesome-branch  #新分支
git switch master  #切回master分支继续操作
git reset --hard HEAD^  #倒退一个revision
git push --force origin master  #强制推到远程仓库（github上）
git push origin my-awesome-branch  #推新分支上来
```

2021-05-20 10:57 UTC, jxlxy1995 commented
搞定

2021-05-20 14:30 UTC, renyuneyun requested changes

2021-05-20 14:30 UTC, renyuneyun commented on sede.py
> +    time = datetime.datetime.strptime(dic[K_DATE], DATE_REPR)
date更符合语义，而不是time。所以应该改下面一行，不是这里。

2021-05-20 14:30 UTC, renyuneyun commented on storage.py
> +        # raise RuntimeError("The requested item {} is not an Event, but a {}".format(id, type(item)))
注释符号删掉吧。还是要抛出异常的，不然的话就得把每个调用的地方都改了，那样就好几个文件了，放在另一个PR里吧。

2021-05-20 14:30 UTC, renyuneyun commented on utils.py
> +        if event is not None:
如果串行的话，这里不用判；如果并行的话，许多地方都得改。反而`get_event`是抛出异常还是返回`None`是次要的东西了。
见上面`get_event`的评论，我倾向于现在先维持原状。

2021-05-21 07:42 UTC, jxlxy1995 commented
第一个修改没问题。  
后两个的话（其实就是一个问题），我遇到的原始情况是想`list`打印`db`中的内容，然后调用到`tabularize_events`，在这之中再调用了`get_event`。此时因为数据库中包含有一个`date`类型的数据，导致程序抛出异常无法查看其它正常的event。  
所以上述情况，不能因为一个`date`导致我没法看其余正常的`event`。当然这只是一个例子，要改对方式很多。我这边先回滚掉这两处修改，晚点你空了直接wx讨论下这个问题。

2021-05-21 09:01 UTC, renyuneyun approved these changes

2021-05-21 09:02 UTC, merged